### ISSUE TITLE
Missing dependency in Baseline

### ISSUE THREAD

**Issue by astares** [Ducasse/NewTools-NewHelpBrowser#7]
New Help browser was announced in https://lists.pharo.org/empathy/thread/Z22KRF4JQWXO3JLPPZX4UOSQZFG34QPU

Tried to load the default baseline in https://github.com/leofrere/NewTools-NewHelpBrowser 
but received an error:

![image](https://user-images.githubusercontent.com/5980033/117066443-04c1b480-ad29-11eb-813a-67b32cc727bb.png)

**Comment by Ducasse** [comment]
Tx
Indeed dependency to TopicBuilder was missing

baseline: spec

	<baseline>
	spec for: #common do: [ 
		spec
			package: #'NewTools-NewHelpBrowser'
			with: [ spec requires: #( #'NewTools-HelpTopicBuilder' ) ];
			package: #'NewTools-NewHelpBrowser-Tests' with: [ 
				spec requires:
						#( #'NewTools-NewHelpBrowser' #'NewTools-HelpTopicBuilder' ) ];
			package: #'NewTools-HelpTopicBuilder';
			package: #'NewTools-HelpTopicBuilder-Tests'
			with: [ spec requires: #( #'NewTools-HelpTopicBuilder' ) ] ]

**Comment by Ducasse** [comment]
Fixed

**Comment by astares** [comment]
Thanks!
